// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN286uyGSOC3U_Lv_waYEN8Jfxr5GLjDs',
    appId: '1:1057259105433:web:c8a8d1ab923ce429a85c08',
    messagingSenderId: '1057259105433',
    projectId: 'sample-demo-ca9cb',
    authDomain: 'sample-demo-ca9cb.firebaseapp.com',
    storageBucket: 'sample-demo-ca9cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7HqOcOiRD2_9LdVLBXack15fc--KsHjw',
    appId: '1:1057259105433:android:664c8a512cd1e765a85c08',
    messagingSenderId: '1057259105433',
    projectId: 'sample-demo-ca9cb',
    storageBucket: 'sample-demo-ca9cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0MylUIXsLmNB1cy1grz464339ogDmvac',
    appId: '1:1057259105433:ios:c4c691e48adec902a85c08',
    messagingSenderId: '1057259105433',
    projectId: 'sample-demo-ca9cb',
    storageBucket: 'sample-demo-ca9cb.firebasestorage.app',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0MylUIXsLmNB1cy1grz464339ogDmvac',
    appId: '1:1057259105433:ios:c4c691e48adec902a85c08',
    messagingSenderId: '1057259105433',
    projectId: 'sample-demo-ca9cb',
    storageBucket: 'sample-demo-ca9cb.firebasestorage.app',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN286uyGSOC3U_Lv_waYEN8Jfxr5GLjDs',
    appId: '1:1057259105433:web:401e9c042e652600a85c08',
    messagingSenderId: '1057259105433',
    projectId: 'sample-demo-ca9cb',
    authDomain: 'sample-demo-ca9cb.firebaseapp.com',
    storageBucket: 'sample-demo-ca9cb.firebasestorage.app',
  );
}
